language: java

jdk:
  - openjdk8
  - openjdk11

services: docker

script:
  - mvn --settings .travis/settings.xml clean verify -B -V

deploy:
  -
    skip_cleanup: true
    provider: script
    script: /bin/bash .travis/deploy.sh
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^v([[:digit:]]+\\.)+[[:digit:]]+(-[[:digit:]]+)?(-SNAPSHOT)?$"
      jdk: openjdk8
